name: esc_pos_printer
description: The library allows to print receipts using an ESC/POS thermal WiFi printer.
version: 4.1.0
homepage: https://github.com/andrey-ushakov/esc_pos_printer
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  charset_converter: ^2.0.0
  esc_pos_utils:
    git:
      url: https://github.com/ramdasoutlogics/esc_pos_utils.git
      ref: af8f273c66dbc81dd66bb61d2cf0a10dc39c18ed
  flutter:
    sdk: flutter
  # esc_pos_utils:
  #   path: ../esc_pos_utils
  image: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
